#!/usr/bin/python2.7

"""Uses some silly screenscraping to submit a FOIA request.

Usage: 
  ./submit_foia --title=<s> --body=<s> --agency=<s> (--allstates|--jurisdiction=<s>)  [--force]

Options:
  -t, --title=<s>           Title of request
  -b, --body=<s>            Body of request
  -A, --allstates           Submit to all states.
  -j, --jurisdiction=<s>    Jurisdiction to send to.
  -a, --agency=<s>          Agency to send to.
  -f, --force               Send without asking.
"""

import selenium
import os
import time

from datetime import datetime
from docopt import docopt
from pprint import pprint
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

states = ["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut",
        "Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa",
        "Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan",
        "Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire",
        "New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma",
        "Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas",
        "Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]

def get_auth(authpath="%s/.foiamachine" % os.environ['HOME']):
    fh = open(authpath, 'r')
    lines = fh.readlines()
    authdict = dict([ j for j in [ i.strip().split(':') for i in lines ] ])
    return authdict 

def login(driver, username, password):
    driver.get("https://beta.foiamachine.org/accounts/login/")

    user_elem = driver.find_element_by_name("username")
    pass_elem = driver.find_element_by_name("password")

    user_elem.send_keys(username)
    pass_elem.send_keys(password)

    pass_elem.send_keys(Keys.RETURN)
    time.sleep(3)

def create_request(driver, title, request_language, jurisdiction, agency, do_force=False):
    driver.get("https://beta.foiamachine.org/foi/create/")

    title_elem = driver.find_element_by_name("title")
    title_elem.send_keys(title)

    text_elem = driver.find_element_by_name("request_language")
    text_elem.send_keys(request_language)

    juris_elem = driver.find_element_by_name("jurisdiction-autocomplete")
    juris_elem.send_keys(jurisdiction)
    time.sleep(1)

    juris_selector = driver.find_element_by_css_selector("body > span")
    juris_index = juris_selector.text.splitlines().index(jurisdiction) + 1

    juris_itm =  driver.find_element_by_css_selector("body > span > span:nth-child(%s)" % juris_index)
    juris_itm.click()

    agency_elem = driver.find_element_by_name("agency-autocomplete")
    agency_elem.send_keys(agency)
    time.sleep(1)

    agency_itm = driver.find_element_by_css_selector("body > span:nth-child(6) > span:nth-child(1)")
    agency_itm.click()

    button = driver.find_element_by_css_selector("body > main > form > button")

    if do_force:
        button.click()
    else:
        do_send = raw_input("y or n ")
        if do_send == "y":
            button.click()
            time.sleep(2)

def parse_args(args):
    agency = args['--agency']
    if args['--allstates']:
        jurisdictions = states
    elif args['--jurisdiction']:
        jurisdictions = [args['--jurisdiction']]
    body = args['--body']
    do_force = args['--force']
    title = args['--title']

    return title, body, jurisdictions, agency, do_force

title, body, jurisdictions, agency, do_force = parse_args(docopt(__doc__))

driver = webdriver.Chrome()

authdict = get_auth()
login(driver, username=authdict['user'], password=authdict['pass'])

for juris in jurisdictions:
    create_request(driver, title, body, juris, agency, do_force)
